### ISSUE TITLE
Please help!  ValueError: list.remove(x): x not in list

### ISSUE THREAD

**Issue by KIueZe** [Sarotti-Lab/ML_J_DP4#1]
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Python\Python311\Scripts\ml_jdp4.exe\__main__.py", line 7, in <module>  File "C:\Python\Python311\Lib\site-packages\ml_jdp4\ml_jdp4.py", line 1006, in 
main
    UnSc_Jotas = J_calculator(Jwtl, coord_mat, hibridization_mat)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\Python311\Lib\site-packages\ml_jdp4\ml_jdp4.py", line 769, in J_calculator
    vecinos_C2.remove(Jwtl[i][k+1]-1)
ValueError: list.remove(x): x not in list

**Comment by KIueZe** [comment]
Sorry, i made mistakes when prepared the exp J data to raise the ValueError! And, a tiny suggestion is that i hope the next version could include type/mismatch check function to make this whole workflow more robust! Thanks!
